### ISSUE TITLE
NoneType object not iterable

### ISSUE THREAD

**Issue by BenMoon** [CFEL-CMI/pymepix#10]
From mail:
```
Process PacketProcessor-10:
Traceback (most recent call last):
 File "/data/parenti/2.10/karabo/extern/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
   self.run()
 File "/data/parenti/2.10/karabo/devices/pymepix/pymepix-develop/pymepix/processing/basepipeline.py", line 194, in run
   output_type, result = self.post_run()
TypeError: 'NoneType' object is not iterable
Process PacketProcessor-11:
Traceback (most recent call last):
 File "/data/parenti/2.10/karabo/extern/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
   self.run()
 File "/data/parenti/2.10/karabo/devices/pymepix/pymepix-develop/pymepix/processing/basepipeline.py", line 194, in run
   output_type, result = self.post_run()
TypeError: 'NoneType' object is not iterable
```

**Comment by jokuha** [comment]
@BenMoon , this needs more info on context.

**Comment by BenMoon** [comment]
This should be solved by https://github.com/CFEL-CMI/pymepix/commit/63e9b927c2e36f9499b39c6422dd7ec2c92e0974
