### ISSUE TITLE
UDPSampler crashes 

### ISSUE THREAD

**Issue by troehling** [CFEL-CMI/pymepix#12]
The UDP samples crashes if no data is received and recording is active.

To reproduce:

1. Launch pymepixviewer
2. Start recording data (without actually receiving any)
3. Stop recording after a few seconds
4. Start recording again
5. Stop recording --> Now the GUI hangs

Stacktrace
```
2021-06-14 16:07:27,069 - pymepix.Raw2Disk - INFO - File /test.raw opening
Process UdpSampler-5:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cfelcmi/timepix/pymepix/pymepix/processing/udpsampler.py", line 311, in run
    copy=False,
  File "/home/cfelcmi/.local/lib/python3.7/site-packages/zmq/sugar/socket.py", line 505, in send
    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 718, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 759, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket
2021-06-14 16:07:32,053 - pymepixviewer.main - INFO - file /test.raw closed
```

**Comment by BenMoon** [comment]
This seems to be an edge case and happens only if the `udpsampler` buffer is empty while recording file should be closed.
