### ISSUE TITLE
python 3.8 throws error when pymepix is closing

### ISSUE THREAD

**Issue by BenMoon** [CFEL-CMI/pymepix#4]
Using Python 3.8 running e.g. test_udpsampler_pytest.py results in an error thrown by threading when the program is closed.
Edit:
Now that I have access to the hardware again, here's the error msg from running `test_udpsampler_pytest.py`:

```
Process UdpSampler-1:
Traceback (most recent call last):
  File "/home/asi/miniconda3/envs/timepix/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/asi/pymepix_develop/pymepix/pymepix/processing/basepipeline.py", line 197, in run
    output_type, result = self.post_run()
  File "/home/asi/pymepix_develop/pymepix/pymepix/processing/udpsampler.py", line 79, in post_run
    packet = np.frombuffer(b''.join(self._packet_buffer), dtype=np.uint64)
TypeError: sequence item 0: expected a bytes-like object, int found
2020-08-29 21:11:06,027 - pymepix.AcqStage-0 - INFO - Join complete
2020-08-29 21:11:06,027 - pymepix.AcqStage-0 - INFO - Stop complete
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/asi/miniconda3/envs/timepix/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/asi/miniconda3/envs/timepix/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "test_udpsampler_pytest.py", line 153, in get_queue_thread
    assert packets_recved == packets * chunk_size
AssertionError
Done
Exception in thread Thread-1:
Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stderr>'> at interpreter shutdown, possibly due to daemon threads
Python runtime state: finalizing (tstate=0x55dac85d02d0)

Thread 0x00007fc746a9d700 (most recent call first):
  File "/home/asi/miniconda3/envs/timepix/lib/python3.8/threading.py", line 1202 in invoke_excepthook
  File "/home/asi/miniconda3/envs/timepix/lib/python3.8/threading.py", line 934 in _bootstrap_inner
  File "/home/asi/miniconda3/envs/timepix/lib/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007fc756551740 (most recent call first):
<no Python frame>
Aborted (core dumped)
```

```

**Comment by jokuha** [comment]
error message?

**Comment by BenMoon** [comment]
I close this issue, as we are already approaching Python 3.12 and the CI test running on versions from 3.7 to 3.11 currently don't show any errors.
